### ISSUE TITLE
TimeStamp(3) 类型数据解析错误的问题

### ISSUE THREAD

**Issue by zhengqiangtan** [liukaixiong/dts-server#1]
你好，如果是 TimeStamp(3)  数据类型的话，dts-server会解析失败

mysql中实际存储值为：2021-01-28 14:12:16.639
```
2021-01-28 11:31:44.908 ERROR 88918 --- [      Thread-18] c.e.d.d.listener.event.DataEventProcess  : 处理数据失败

java.lang.NumberFormatException: For input string: "1611804650.445000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.elab.data.dts.utils.DataParseUtils.getTypeValue(DataParseUtils.java:155)
	at com.elab.data.dts.utils.DataParseUtils.parseUpdateField(DataParseUtils.java:122)
	at com.elab.data.dts.utils.DataParseUtils.parseDML(DataParseUtils.java:198)
	at com.elab.data.dts.listener.event.DataEventProcess.parseTable(DataEventProcess.java:41)
	at com.elab.data.dts.listener.event.AbstractEventProcess.processEvent(AbstractEventProcess.java:123)
	at com.elab.data.dts.listener.RecordConsumerListener.consume(RecordConsumerListener.java:39)
	at com.elab.data.dts.recordprocessor.EtlRecordProcessor.run(EtlRecordProcessor.java:77)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by zhengqiangtan** [comment]
解决：注释掉如下代码
```
//                timestampBuilder.append(timestamp.getTimestamp());
//                if (null != timestamp.getMillis() && timestamp.getMillis() > 0) {
//                    timestampBuilder.append('.');
//                    String millis = java.lang.Integer.toString(timestamp.getMillis());
//                    timestampBuilder.append(MILLIS_PREFIX[6 - millis.length()]).append(millis);
//                }
```
